### PR TITLE
Update [NVY-30] Caracal.md

### PR DESCRIPTION
**Pull request by unkwntech**
Adding missiles since caracal isn't damage locked and nanite paste

### CODE REVIEW

**Comment by porowns** [comment]
I intentionally didn't add the missiles here to reduce the choice paralysis. Do we think that adding them will be fine?

**Comment by unkwntech** [comment]
I can see the argument for not adding them all, but IMO at least 1 other option would be good for the cases when thermal is not a good choice.

**Comment by Furl0w** [comment]
Let's say that we add Nova: Thermal is only a bad choice against armor/gallente T2 ships, and it gives a mix to counter a bit reactive if caracal had to face them. Fine to keep the paste. Remove Mjolnir and Scourge and I merge :)

**Comment by Furl0w** [comment]
Outdated

**Pull request closed without merging**
